<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\PaymentLedger\Friday.Modules.PaymentLedger.Application\Friday.Modules.PaymentLedger.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\PaymentLedger\Friday.Modules.PaymentLedger.Domain\Friday.Modules.PaymentLedger.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\PaymentLedger\Friday.Modules.PaymentLedger.Infrastructure\Friday.Modules.PaymentLedger.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
