// <auto-generated />
using System;
using Friday.Modules.PaymentLedger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Friday.Modules.PaymentLedger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaymentLedgerDbContext))]
    [Migration("20260812053730_PaymentLedgerAuditAndIntegrity")]
    partial class PaymentLedgerAuditAndIntegrity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payment_ledger")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Friday.Modules.PaymentLedger.Domain.Ledger.FinancialAuditRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("FinancialTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LedgerAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RefId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "OccurredOnUtc");

                    b.HasIndex("FinancialTransactionId", "OccurredOnUtc");

                    b.HasIndex("LedgerAccountId", "OccurredOnUtc");

                    b.ToTable("financial_audit_records", "payment_ledger");
                });

            modelBuilder.Entity("Friday.Modules.PaymentLedger.Domain.Ledger.FinancialTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19)
                        .HasColumnType("numeric(19,0)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("DestinationAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OriginalTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PostedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReversalTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("OriginalTransactionId")
                        .IsUnique()
                        .HasFilter("\"OriginalTransactionId\" IS NOT NULL");

                    b.HasIndex("ReversalTransactionId")
                        .IsUnique();

                    b.HasIndex("DestinationAccountId", "PostedOnUtc");

                    b.HasIndex("PostedOnUtc", "Id");

                    b.HasIndex("SourceAccountId", "PostedOnUtc");

                    b.ToTable("financial_transactions", "payment_ledger", t =>
                        {
                            t.HasCheckConstraint("CK_financial_transactions_accounts", "\"SourceAccountId\" <> \"DestinationAccountId\"");

                            t.HasCheckConstraint("CK_financial_transactions_amount", "\"Amount\" > 0 AND \"Amount\" = trunc(\"Amount\")");

                            t.HasCheckConstraint("CK_financial_transactions_currency", "\"Currency\" = 'VND'");

                            t.HasCheckConstraint("CK_financial_transactions_status", "\"Status\" IN ('Posted','Reversed')");

                            t.HasCheckConstraint("CK_financial_transactions_type", "\"Type\" IN ('InternalTransfer','Reversal')");
                        });
                });

            modelBuilder.Entity("Friday.Modules.PaymentLedger.Domain.Ledger.IdempotencyRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RefId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "Operation", "RefId")
                        .IsUnique();

                    b.ToTable("idempotency_records", "payment_ledger");
                });

            modelBuilder.Entity("Friday.Modules.PaymentLedger.Domain.Ledger.Journal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PostedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("journals", "payment_ledger");
                });

            modelBuilder.Entity("Friday.Modules.PaymentLedger.Domain.Ledger.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19)
                        .HasColumnType("numeric(19,0)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("LedgerAccountId", "JournalId");

                    b.ToTable("journal_entries", "payment_ledger", t =>
                        {
                            t.HasCheckConstraint("CK_journal_entries_amount", "\"Amount\" > 0 AND \"Amount\" = trunc(\"Amount\")");

                            t.HasCheckConstraint("CK_journal_entries_currency", "\"Currency\" = 'VND'");

                            t.HasCheckConstraint("CK_journal_entries_direction", "\"Direction\" IN ('Debit','Credit')");
                        });
                });

            modelBuilder.Entity("Friday.Modules.PaymentLedger.Domain.Ledger.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("AvailableBalance")
                        .HasPrecision(19)
                        .HasColumnType("numeric(19,0)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountRef")
                        .IsUnique();

                    b.ToTable("ledger_accounts", "payment_ledger", t =>
                        {
                            t.HasCheckConstraint("CK_ledger_accounts_balance", "\"AvailableBalance\" >= 0 AND \"AvailableBalance\" = trunc(\"AvailableBalance\")");

                            t.HasCheckConstraint("CK_ledger_accounts_currency", "\"Currency\" = 'VND'");

                            t.HasCheckConstraint("CK_ledger_accounts_status", "\"Status\" IN ('Active','Suspended')");
                        });
                });

            modelBuilder.Entity("Friday.Modules.PaymentLedger.Domain.Ledger.FinancialTransaction", b =>
                {
                    b.HasOne("Friday.Modules.PaymentLedger.Domain.Ledger.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Friday.Modules.PaymentLedger.Domain.Ledger.FinancialTransaction", null)
                        .WithOne()
                        .HasForeignKey("Friday.Modules.PaymentLedger.Domain.Ledger.FinancialTransaction", "OriginalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Friday.Modules.PaymentLedger.Domain.Ledger.FinancialTransaction", null)
                        .WithOne()
                        .HasForeignKey("Friday.Modules.PaymentLedger.Domain.Ledger.FinancialTransaction", "ReversalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Friday.Modules.PaymentLedger.Domain.Ledger.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Friday.Modules.PaymentLedger.Domain.Ledger.Journal", b =>
                {
                    b.HasOne("Friday.Modules.PaymentLedger.Domain.Ledger.FinancialTransaction", null)
                        .WithOne("Journal")
                        .HasForeignKey("Friday.Modules.PaymentLedger.Domain.Ledger.Journal", "TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Friday.Modules.PaymentLedger.Domain.Ledger.JournalEntry", b =>
                {
                    b.HasOne("Friday.Modules.PaymentLedger.Domain.Ledger.Journal", null)
                        .WithMany("Entries")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Friday.Modules.PaymentLedger.Domain.Ledger.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("LedgerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Friday.Modules.PaymentLedger.Domain.Ledger.FinancialTransaction", b =>
                {
                    b.Navigation("Journal")
                        .IsRequired();
                });

            modelBuilder.Entity("Friday.Modules.PaymentLedger.Domain.Ledger.Journal", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
