// <auto-generated />
using System;
using Friday.Modules.Customer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Friday.Modules.Customer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customer")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Friday.Modules.Customer.Domain.Auditing.CustomerChangeAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ChangedFieldsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RetainUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("RetainUntilUtc");

                    b.HasIndex("CustomerId", "OccurredOnUtc");

                    b.ToTable("customer_change_audits", "customer");
                });

            modelBuilder.Entity("Friday.Modules.Customer.Domain.Customers.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CitizenDocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CitizenDocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CitizenIdMasked")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CitizenIssuingCountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("OpenedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("CustomerCode")
                        .IsUnique();

                    b.HasIndex("OpenedOnUtc", "Id");

                    b.HasIndex("CitizenDocumentType", "CitizenIssuingCountryCode", "CitizenDocumentNumber")
                        .IsUnique();

                    b.HasIndex("Status", "OpenedOnUtc", "Id");

                    b.ToTable("customers", "customer", t =>
                        {
                            t.HasCheckConstraint("CK_customers_country", "\"CitizenIssuingCountryCode\" ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("CK_customers_document_format", "(\"CitizenDocumentType\" = 'VietnamCitizenId' AND \"CitizenIssuingCountryCode\" = 'VN' AND \"CitizenDocumentNumber\" ~ '^[0-9]{12}$') OR (\"CitizenDocumentType\" = 'Passport' AND \"CitizenDocumentNumber\" ~ '^[A-Z0-9]{6,20}$')");

                            t.HasCheckConstraint("CK_customers_document_mask", "\"CitizenIdMasked\" = repeat('*', greatest(char_length(\"CitizenDocumentNumber\") - 4, 0)) || right(\"CitizenDocumentNumber\", least(4, char_length(\"CitizenDocumentNumber\")))");

                            t.HasCheckConstraint("CK_customers_document_type", "\"CitizenDocumentType\" IN ('VietnamCitizenId', 'Passport')");

                            t.HasCheckConstraint("CK_customers_status", "\"Status\" IN ('Active', 'Suspended', 'Closed')");
                        });
                });

            modelBuilder.Entity("Friday.Modules.Customer.Domain.Auditing.CustomerChangeAudit", b =>
                {
                    b.HasOne("Friday.Modules.Customer.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
